### ISSUE TITLE
The version on PyPI cannot be installed

### ISSUE THREAD

**Issue by Jackenmen** [salabim/unrepl#1]
```
❯ virtualenv test-unrepl 
created virtual environment CPython3.10.4.final.0-64 in 274ms
  creator CPython3Posix(dest=/tmp/test-unrepl, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/ubuntu/.local/share/virtualenv)
    added seed packages: pip==22.2.2, setuptools==65.0.1, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

❯ . test-unrepl/bin/activate

❯ pip install unrepl      
Collecting unrepl
  Downloading unrepl-1.0.5.tar.gz (5.1 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-34kwewcr/unrepl_6812259dbfc343d6aa0dd8675f014bfe/setup.py", line 3, in <module>
          readme = open("../readme.md").read()
      FileNotFoundError: [Errno 2] No such file or directory: '../readme.md'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by salabim** [comment]
Thanks for the observation. I will fix that next week.

**Comment by salabim** [comment]
Fixed
